CREATE TABLE activity
(
    id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255),
    code        VARCHAR(255),
    date        TIMESTAMP,
    duration    INT                                  NOT NULL,
    CONSTRAINT pk_activity PRIMARY KEY (id)
);
CREATE TABLE feedback
(
    id    INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type  VARCHAR(255),
    date  TIMESTAMP,
    grade INT                                  NOT NULL,
    CONSTRAINT pk_feedback PRIMARY KEY (id)
);
ALTER TABLE feedback
    ADD activity_id INT;

ALTER TABLE feedback
    ALTER COLUMN activity_id SET NOT NULL;

ALTER TABLE feedback
    ADD CONSTRAINT FK_FEEDBACK_ON_ACTIVITY FOREIGN KEY (activity_id) REFERENCES activity (id);
ALTER TABLE activity
    DROP COLUMN id;

ALTER TABLE activity
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;
ALTER TABLE activity
    DROP COLUMN id;

ALTER TABLE activity
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;
ALTER TABLE feedback
    DROP COLUMN activity_id;

ALTER TABLE feedback
    DROP COLUMN id;

ALTER TABLE feedback
    ADD activity_id BIGINT NOT NULL;

ALTER TABLE feedback
    ADD CONSTRAINT FK_FEEDBACK_ON_ACTIVITY FOREIGN KEY (activity_id) REFERENCES activity (id);

ALTER TABLE feedback
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;